# Generated by Django 4.2.7 on 2025-07-18 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("board", models.CharField(default="---------", max_length=9)),
                ("player_x", models.CharField(max_length=100)),
                ("player_o", models.CharField(blank=True, max_length=100, null=True)),
                ("current_turn", models.CharField(default="X", max_length=1)),
                ("winner", models.CharField(blank=True, max_length=1, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
